### ISSUE TITLE
Adding Data Binary

### ISSUE THREAD

**Issue by mariopattan** [qeet/IMPORTJSONAPI#8]
Hi @qeet , is it possible to insert data binary in importjsonapi?

I tried the curl method:POST on Postman and it worked. Here's the curl code:

`curl 'https://portal.grab.com/foodweb/v2/search' \
  -H 'authority: portal.grab.com' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://food.grab.com' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  --data-binary '{"latlng":"-6.1164339,106.7896514","keyword":"kopi","offset":0,"pageSize":32}' \
  --compressed`

and the code I tried using importjsonapi: 
`=IMPORTJSONAPI("https://portal.grab.com/foodweb/v2/search","$.target","target","method=post","headers={'authority':'portal.grab.com','content-type':'application/json;charset=UTF-8','origin':'https://food.grab.com','sec-fetch-site': 'same-site','sec-fetch-mode':'cors','sec-fetch-dest':'empty')")'

It return " ERROR: Invalid JSON and I still need to add the data binary.

Thank you

**Comment by qeet** [comment]
The error in your code was that you need to have a curly brace '}' instead of a round brace')' right at the end after the 'empy' word. Here is a working version of the code including the data binary:

`=IMPORTJSONAPI("https://portal.grab.com/foodweb/v2/search","$.searchResult.searchMerchants[*]","id, address","method=post","contentType=application/json", "headers={'authority':'portal.grab.com', 'origin':'https://food.grab.com','sec-fetch-site': 'same-site','sec-fetch-mode':'cors','sec-fetch-dest':'empty'}", "payload={'latlng':'-6.1164339,106.7896514','keyword':'kopi','offset':0,'pageSize':32}")` 

Note that the content-type needs to be defined as a separate parameter and not as part of the headers.
